[package]
name = "release-drafter-practice"
version = "0.1.0"
authors = ["Kanchi Shimono <dev.kanchi.shimono@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
